package ventanas;

import Batallas.Batalla;
import Componentes.Animales.Elefante;
import Componentes.Animales.Tigre;
import Componentes.Componente;
import Componentes.Personas.Caballeria;
import Componentes.Personas.Infanteria;
import DataBase.MySQLConnection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esther
 */
public class VentanaEjercito1 extends javax.swing.JFrame {
    
    private final MySQLConnection mysql = MySQLConnection.getInstance();
    private final Batalla batalla = Batalla.getInstance();
    
    public VentanaEjercito1() {
        
        initComponents();
        
        this.buttonGroup1.add(this.radioButtonAnadirInfanteria);
        this.buttonGroup1.add(this.radioButtonAnadirCaballeria);
        this.buttonGroup1.add(this.radioButtonAnadirGeneral);
        this.buttonGroup1.add(this.radiobuttonAnadirElefante);
        this.buttonGroup1.add(this.radioButtonAnadirTigre);
        this.buttonGroup1.add(this.radioButtonEliminarUnidad);
        
        
        this.textFieldNobreEjercito.addKeyListener( new KeyAdapter() {
            public void keyTyped(KeyEvent e){
               batalla.getEjercito1().setNombre(textFieldNobreEjercito.getText().trim());
               updateComponentState();
           }
        });
        
       
        //Logica del tamaño y localizacion de la ventana
        this.updateComponentState();
        setSize(720, 470);
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonConfirmar = new javax.swing.JButton();
        buttonSleccionar = new javax.swing.JButton();
        textFieldNobreEjercito = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelSalud = new javax.swing.JLabel();
        radioButtonAnadirInfanteria = new javax.swing.JRadioButton();
        radioButtonAnadirCaballeria = new javax.swing.JRadioButton();
        radioButtonAnadirGeneral = new javax.swing.JRadioButton();
        radiobuttonAnadirElefante = new javax.swing.JRadioButton();
        radioButtonAnadirTigre = new javax.swing.JRadioButton();
        radioButtonEliminarUnidad = new javax.swing.JRadioButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelSalud = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(255, 204, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "ID", "Ataque", "Defensa", "Salud"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 380, 130));

        buttonConfirmar.setBackground(new java.awt.Color(204, 153, 0));
        buttonConfirmar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        buttonSleccionar.setBackground(new java.awt.Color(204, 153, 0));
        buttonSleccionar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonSleccionar.setText("Seleccionar");
        buttonSleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        textFieldNobreEjercito.setBackground(new java.awt.Color(255, 204, 102));
        textFieldNobreEjercito.setForeground(new java.awt.Color(255, 255, 255));
        textFieldNobreEjercito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNobreEjercitoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldNobreEjercito, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 62, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Ejercito 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, -1));

        jLabelSalud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSalud.setForeground(new java.awt.Color(153, 51, 0));
        jLabelSalud.setText("Salud total");
        jPanel1.add(jLabelSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        radioButtonAnadirInfanteria.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirInfanteria.setText("Añadir Infantería");
        radioButtonAnadirInfanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAnadirInfanteriaActionPerformed(evt);
            }
        });
        jPanel1.add(radioButtonAnadirInfanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        radioButtonAnadirCaballeria.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirCaballeria.setText("Añadir Caballeria");
        jPanel1.add(radioButtonAnadirCaballeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        radioButtonAnadirGeneral.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirGeneral.setText("Añadir General");
        jPanel1.add(radioButtonAnadirGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        radiobuttonAnadirElefante.setForeground(new java.awt.Color(153, 0, 0));
        radiobuttonAnadirElefante.setText("Añadir Elefante");
        jPanel1.add(radiobuttonAnadirElefante, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        radioButtonAnadirTigre.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirTigre.setText("Añadir Tigre");
        jPanel1.add(radioButtonAnadirTigre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        radioButtonEliminarUnidad.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonEliminarUnidad.setText("Eliminar Unidad");
        jPanel1.add(radioButtonEliminarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(153, 51, 0));
        jLabelTotal.setText("Peso Total");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 360, 160, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura de pantalla 2024-03-18 211437_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        labelSalud.setText("jLabel5");
        jPanel1.add(labelSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 60, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        VentanaEjercito2 newframe = new VentanaEjercito2 ();//Logica que enlaza con la siguiente ventana

        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonSleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSleccionarActionPerformed
  
        try {
            if (radioButtonAnadirInfanteria.isSelected()) this.batalla.getEjercito1().agregarComponente(new Infanteria());
            if (radioButtonAnadirCaballeria.isSelected()) this.batalla.getEjercito1().agregarComponente(new Caballeria());
            if (radioButtonAnadirGeneral.isSelected()) this.batalla.getEjercito1().agregarComponente(this.mysql.getRandomGeneral());
            if (radiobuttonAnadirElefante.isSelected()) this.batalla.getEjercito1().agregarComponente(new Elefante());
            if (radioButtonAnadirTigre.isSelected()) this.batalla.getEjercito1().agregarComponente(new Tigre());
            if (radioButtonEliminarUnidad.isSelected()){
                final int fila = jTable2.getSelectedRow();
                final String nombre = (String) jTable2.getModel().getValueAt(fila, 1);
                this.batalla.getEjercito1().eliminarComponenteConNombre(nombre);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            this.updateComponentState();
        }
    }//GEN-LAST:event_buttonSleccionarActionPerformed

    private void textFieldNobreEjercitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNobreEjercitoActionPerformed

    }//GEN-LAST:event_textFieldNobreEjercitoActionPerformed

    private void radioButtonAnadirInfanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAnadirInfanteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAnadirInfanteriaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEjercito1().setVisible(true);
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelSalud;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelSalud;
    private javax.swing.JRadioButton radioButtonAnadirCaballeria;
    private javax.swing.JRadioButton radioButtonAnadirGeneral;
    private javax.swing.JRadioButton radioButtonAnadirInfanteria;
    private javax.swing.JRadioButton radioButtonAnadirTigre;
    private javax.swing.JRadioButton radioButtonEliminarUnidad;
    private javax.swing.JRadioButton radiobuttonAnadirElefante;
    private javax.swing.JTextField textFieldNobreEjercito;
    // End of variables declaration//GEN-END:variables

    private void updateComponentState() {
        
        this.buttonConfirmar.setEnabled(batalla.getEjercito1().valido());
        List<String[]> listArray = new ArrayList<>();
        for(Componente c : this.batalla.getEjercito1().getComponentes()){
            listArray.add(c.toStringArray());
        }
        
        //System.out.println(this.batalla.getEjercito1().getComponentes().size() + " Unidades");
        
        
        String[][] tableDataModel = listArray.stream().toArray(String[][]::new);
        
        //System.out.println(tableDataModel);
        
        this.jTable2.setModel(new DefaultTableModel(
                tableDataModel,
                new String [] {"Tipo", "Nombre", "Ataque", "Defensa", "Salud"}
        ));
        
        this.jLabelSalud.setText("Salud Total: " + this.batalla.getEjercito1().getSalud());
        this.jLabelTotal.setText("Peso Total: " + this.batalla.getEjercito1().getSaldoPeso());
        
        pack();
    }

}

