package ventanas;

import Batallas.Batalla;
import Componentes.Animales.Elefante;
import Componentes.Animales.Tigre;
import Componentes.Componente;
import Componentes.Personas.Caballeria;
import Componentes.Personas.Infanteria;
import DataBase.MySQLConnection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esther
 */
public class VentanaEjercito2 extends javax.swing.JFrame {
    
    private final MySQLConnection mysql = MySQLConnection.getInstance();
    private final Batalla batalla = Batalla.getInstance();
    private javax.swing.ButtonGroup buttonGroup1;
    
    public VentanaEjercito2() {
        
        initComponents();
        
        this.buttonGroup1 = new ButtonGroup();
        
        this.buttonGroup1.add(this.radioButtonAnadirInfanteria);
        this.buttonGroup1.add(this.radioButtonAnadirCaballeria);
        this.buttonGroup1.add(this.radioButtonAnadirGeneral);
        this.buttonGroup1.add(this.radiobuttonAnadirElefante);
        this.buttonGroup1.add(this.radioButtonAnadirTigre);
        this.buttonGroup1.add(this.radioButtonEliminarUnidad);
        
        this.textFieldNobreEjercito.addKeyListener( new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                batalla.getEjercito2().setNombre(textFieldNobreEjercito.getText().trim());
                updateComponentState();
            }
        });
        
        this.updateComponentState();
        setSize(720, 470);
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelsalud = new javax.swing.JLabel();
        jLabeEjercitol2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonConfirmar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        radioButtonAnadirInfanteria = new javax.swing.JRadioButton();
        radioButtonAnadirCaballeria = new javax.swing.JRadioButton();
        radioButtonAnadirGeneral = new javax.swing.JRadioButton();
        radiobuttonAnadirElefante = new javax.swing.JRadioButton();
        radioButtonAnadirTigre = new javax.swing.JRadioButton();
        radioButtonEliminarUnidad = new javax.swing.JRadioButton();
        buttonSeleccionar = new javax.swing.JButton();
        textFieldNobreEjercito = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelsalud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelsalud.setForeground(new java.awt.Color(153, 0, 0));
        jLabelsalud.setText("Salud");
        jPanel1.add(jLabelsalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 160, -1));

        jLabeEjercitol2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabeEjercitol2.setForeground(new java.awt.Color(153, 51, 0));
        jLabeEjercitol2.setText("Ejercito 2");
        jPanel1.add(jLabeEjercitol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 80));

        jTable2.setBackground(new java.awt.Color(255, 204, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "ID", "Ataque", "Defensa", "Salud"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 370, 110));

        buttonConfirmar.setBackground(new java.awt.Color(204, 153, 0));
        buttonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 100, 30));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(204, 51, 0));
        jLabelTotal.setText("Total");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, -1));

        radioButtonAnadirInfanteria.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirInfanteria.setText("Añadir Infanteria");
        radioButtonAnadirInfanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAnadirInfanteriaActionPerformed(evt);
            }
        });
        jPanel1.add(radioButtonAnadirInfanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, -1));

        radioButtonAnadirCaballeria.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirCaballeria.setText("Añadir Caballería");
        radioButtonAnadirCaballeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAnadirCaballeriaActionPerformed(evt);
            }
        });
        jPanel1.add(radioButtonAnadirCaballeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        radioButtonAnadirGeneral.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirGeneral.setText("Añadir General");
        jPanel1.add(radioButtonAnadirGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        radiobuttonAnadirElefante.setForeground(new java.awt.Color(153, 0, 0));
        radiobuttonAnadirElefante.setText("Añadir Elefante");
        jPanel1.add(radiobuttonAnadirElefante, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        radioButtonAnadirTigre.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonAnadirTigre.setText("Añadir Tigre");
        jPanel1.add(radioButtonAnadirTigre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        radioButtonEliminarUnidad.setForeground(new java.awt.Color(153, 0, 0));
        radioButtonEliminarUnidad.setText("Eliminar Unidad");
        jPanel1.add(radioButtonEliminarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        buttonSeleccionar.setBackground(new java.awt.Color(204, 153, 0));
        buttonSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSeleccionar.setText("Seleccionar");
        buttonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, 30));

        textFieldNobreEjercito.setBackground(new java.awt.Color(255, 204, 102));
        textFieldNobreEjercito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNobreEjercitoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldNobreEjercito, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura de pantalla 2024-03-18 211437.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNobreEjercitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNobreEjercitoActionPerformed

    }//GEN-LAST:event_textFieldNobreEjercitoActionPerformed

    private void buttonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarActionPerformed
        try {
            if (radioButtonAnadirInfanteria.isSelected()) this.batalla.getEjercito2().agregarComponente(new Infanteria());
            if (radioButtonAnadirCaballeria.isSelected()) this.batalla.getEjercito2().agregarComponente(new Caballeria());
            if (radioButtonAnadirGeneral.isSelected()) this.batalla.getEjercito2().agregarComponente(this.mysql.getRandomGeneral());
            if (radiobuttonAnadirElefante.isSelected()) this.batalla.getEjercito2().agregarComponente(new Elefante());
            if (radioButtonAnadirTigre.isSelected()) this.batalla.getEjercito2().agregarComponente(new Tigre());
            if (radioButtonEliminarUnidad.isSelected()){
                final int fila = jTable2.getSelectedRow();
                final String nombre = (String) jTable2.getModel().getValueAt(fila, 1);
                this.batalla.getEjercito2().eliminarComponenteConNombre(nombre);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            this.updateComponentState();
        }
    }//GEN-LAST:event_buttonSeleccionarActionPerformed

    private void radioButtonAnadirCaballeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAnadirCaballeriaActionPerformed

    }//GEN-LAST:event_radioButtonAnadirCaballeriaActionPerformed

    private void radioButtonAnadirInfanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAnadirInfanteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAnadirInfanteriaActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        
        VentanaBatalla newframe = new VentanaBatalla();

        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_buttonConfirmarActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEjercito2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonSeleccionar;
    private javax.swing.JLabel jLabeEjercitol2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelsalud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton radioButtonAnadirCaballeria;
    private javax.swing.JRadioButton radioButtonAnadirGeneral;
    private javax.swing.JRadioButton radioButtonAnadirInfanteria;
    private javax.swing.JRadioButton radioButtonAnadirTigre;
    private javax.swing.JRadioButton radioButtonEliminarUnidad;
    private javax.swing.JRadioButton radiobuttonAnadirElefante;
    private javax.swing.JTextField textFieldNobreEjercito;
    // End of variables declaration//GEN-END:variables

    private void updateComponentState() {
        
        this.buttonConfirmar.setEnabled(batalla.getEjercito2().valido());
        List<String[]> listArray = new ArrayList<>();
        for(Componente c : this.batalla.getEjercito2().getComponentes()){
            listArray.add(c.toStringArray());
        }
        
        //System.out.println(this.batalla.getEjercito2().getComponentes().size() + " Unidades");
        
        
        String[][] tableDataModel = listArray.stream().toArray(String[][]::new);
        
        //System.out.println(tableDataModel);
        
        this.jTable2.setModel(new DefaultTableModel(
                tableDataModel,
                new String [] {"Tipo", "Nombre", "Ataque", "Defensa", "Salud"}
        ));
        
        this.jLabelsalud.setText("Salud Total: " + this.batalla.getEjercito2().getSalud());
        this.jLabelTotal.setText("Peso Total: " + this.batalla.getEjercito2().getSaldoPeso());
        
        pack();
    }
}